name: CI

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: get grails and build
        run: |
          ls -l
          #   set -e
          #    export EXIT_STATUS=0
          #  curl -s "https://get.sdkman.io" | bash
          #   source "$HOME/.sdkman/bin/sdkman-init.sh"
          #   sdk install grails 2.5.6
          #  grails -version
          #  grails war /rap.war -Dgrails.project.work.dir=work --stacktrace
          
