name: CI
permissions:
  contents: write
on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: get grails and build war file
        run: |
          set -e
          export EXIT_STATUS=0
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install grails 2.5.6
          grails -version
          whereis grails 
          #cd /home/runner/.sdkman/candidates/grails/2.5.6/bin/
          ls -l
          grails war /rap.war --stacktrace
